---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.9

inputs:
- name: git-omen

run:
  path: /bin/sh
  args:
  - -exc
  - "go build -o omen-build/omen-linux64"

outputs:
- omen-build

params:
  GOOS: linux
  GOARCH: amd64
